Add diffblue tests
Diffblue-benchmarks/Looly-hutool pull request #1
Opened 2018-11-01 12:05 UTC by diffblue-assistant

All tests help to cover functions not yet covered in side covered test classes

2018-11-01 12:07 UTC, JohnLBergqvist requested changes
You need to add Apache License Headers to this, and (in order to credit us as Copyright for just our tests), put our tests in separate files. If you disagree, we need to have a discussion about this involving Mel & @peterschrammel here, because i'm wondering if doing this is partly why our tests get rejected.

2018-11-01 14:49 UTC, paulkennethkent commented on hutool-core/src/test/java/cn/hutool/core/collection/IterUtilTest.java
>  public class IterUtilTest {
I would say that these tests are less interesting than the rest but the choice is yours.

2018-11-05 14:32 UTC, petersear approved these changes

2018-11-05 14:56 UTC, JohnLBergqvist approved these changes

2019-07-02 14:39 UTC, closed without merging